# C:\Users\j_tagami\CiquestWebApp\ciquest_model\migrations\0001_initial.py
# Generated by Django 5.2.8 on 2025-11-12 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('required_points', models.IntegerField()),
                ('max_challenges_per_day', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('business_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('store_description', models.TextField(blank=True, null=True)),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', '審査中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOwner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_points', models.IntegerField()),
                ('type', models.CharField(choices=[('common', '共通'), ('store_specific', '店舗独自')], default='common', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.store')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('reward_points', models.IntegerField()),
                ('type', models.CharField(choices=[('PURCHASE', '購入'), ('PHOTO', '写真投稿'), ('VISIT', '来店')], max_length=20)),
                ('quest_type', models.CharField(choices=[('common', '共通'), ('store_specific', '店舗独自')], max_length=20)),
                ('reward_type', models.CharField(choices=[('points', 'ポイント'), ('coupon', 'クーポン'), ('service', 'サービス')], default='points', max_length=20)),
                ('reward_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reward_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.coupon')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.store')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.storeowner'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.rank')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStamp',
            fields=[
                ('stamp_id', models.AutoField(primary_key=True, serialize=False)),
                ('stamps_count', models.IntegerField(default=0)),
                ('reward_given', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('user_challenge_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', '進行中'), ('cleared', 'クリア'), ('retired', 'リタイア')], default='in_progress', max_length=20)),
                ('proof_image', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by_store', models.BooleanField(default=False)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('user_coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.user')),
            ],
        ),
        migrations.CreateModel(
            name='StoreTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.storeowner')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.store')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciquest_model.tag')),
            ],
            options={
                'unique_together': {('store', 'tag')},
            },
        ),
    ]
