# Generated by Django 5.2.8 on 2025-11-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='publish_to_shop',
            field=models.BooleanField(default=False),
        ),
    ]
