# Generated by Django 5.2.8 on 2025-11-14 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0002_coupon_publish_to_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStampSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_stamps', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stamp_setting', to='ciquest_model.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStampReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_threshold', models.PositiveSmallIntegerField()),
                ('reward_type', models.CharField(choices=[('coupon', 'クーポン'), ('service', 'サービス')], max_length=20)),
                ('reward_service_desc', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('reward_coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.coupon')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='ciquest_model.storestampsetting')),
            ],
            options={
                'ordering': ['display_order', 'stamp_threshold'],
            },
        ),
    ]
