# Generated by Django 5.2.8 on 2025-11-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0003_storestampsetting_storestampreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
