# Generated by Django 5.2.8 on 2025-11-17 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0004_adminaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminInquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('unread', '未読'), ('in_progress', '対応中'), ('resolved', '対応済み')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.challenge')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciquest_model.store')),
            ],
        ),
    ]
