# Generated by Django 5.2.8 on 2025-11-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0005_challenge_is_banned_admininquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='verification_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
