# Generated by Django 5.2.8 on 2025-11-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0006_storeowner_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeowner',
            name='business_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='storeowner',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
