# Generated by Django 5.2.8 on 2025-11-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0002_store_mobile_fields'),
        ('ciquest_model', '0011_adminaccount_soft_delete_restore'),
    ]

    operations = [
    ]
