# Generated by Django 5.2.8 on 2026-01-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciquest_model', '0012_merge_20251125_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='publish_to_shop',
            field=models.BooleanField(default=True),
        ),
    ]
