# Generated by Codex on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciquest_model", "0019_remove_stamp_day_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_rank_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
