# Generated by Codex on 2026-01-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ciquest_model", "0020_user_last_rank_reset_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("badge_id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("badge", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ciquest_model.badge")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ciquest_model.user")),
            ],
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(fields=("user", "badge"), name="uq_user_badge"),
        ),
    ]
