# C:\Users\j_tagami\CiquestWebApp\ciquest_server\settings.py
"""
Django settings for ciquest_server project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# ============================================================
# BASE PATH
# ============================================================
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# SECURITY SETTINGS
# ============================================================
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-$lb9_cepk#vl@5=8sqp888)=d7r4c+qv^+7yt7ixtz76n^j#5*')
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"
_default_allowed = [
    "ciquestwebapp.onrender.com",
    "localhost",
    "127.0.0.1",
    "44.222.189.208",
    "ec2-44-222-189-208.compute-1.amazonaws.com",
]
_env_allowed = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()
]
# Render 固有のホスト名を自動で許可（環境変数 RENDER_EXTERNAL_HOSTNAME がある場合）
_render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    _env_allowed.append(_render_host)
ALLOWED_HOSTS = _env_allowed or _default_allowed


# ============================================================
# APPLICATIONS
# ============================================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    

    # Ciquest apps
    'owner',
    'admin_panel',
    'ciquest_model', 
    'django_extensions',
    "widget_tweaks",
]


# ============================================================
# MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL / WSGI CONFIG
# ============================================================
ROOT_URLCONF = 'ciquest_server.urls'
WSGI_APPLICATION = 'ciquest_server.wsgi.application'


# ============================================================
# TEMPLATES
# ============================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # 共通テンプレートフォルダ
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# ============================================================
# DATABASE
# ============================================================
ENV = os.environ.get("DJANGO_ENV", "development")

if ENV == "production":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'ciquest_db',
            'USER': 'root',               # ← 本番DBユーザーに変更
            'PASSWORD': 'password',       # ← 本番用に変更
            'HOST': 'localhost',
            'PORT': '3306',
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# DATABASE_URL が設定されている場合は優先して利用（Render/Postgres 用）
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'
USE_I18N = True
USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# WhiteNoise で圧縮・キャッシュ付与した静的ファイルを配信
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ============================================================
# DEFAULTS
# ============================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7日間保持
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # ブラウザ閉じてもログイン保持
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/owner/dashboard/'

PUBLIC_API_KEY = os.environ.get("PHONE_API_KEY", "")

ADMIN_LOGIN_ACCOUNTS = [
    {"identifier": "admin", "password": "9999"},
]

# Public API key for phone clients (header: phone-API-key)
PHONE_API_KEY = os.environ.get("PHONE_API_KEY", "")



# メール送信設定（本番では環境変数で上書き）

# ?????????????????????
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "1") == "1"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@ciquest.local")


